#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'
shopt -s nullglob nocaseglob

# modern bash version check
! [ "${BASH_VERSINFO:-0}" -ge 4 ] && echo "This script requires bash v4 or later" && exit 1

# disable cloud-init network config
sudo tee /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg <<< "network: {config: disabled}"

# cleanup old network config
sudo rm -f /etc/netplan/50-cloud-init.yaml

# update netplan config
sudo tee /etc/netplan/10-gk-minecraft.yaml <<EOF
# static IP
network:
  version: 2
  ethernets:
    eth0:
      dhcp4: true
      nameservers:
        addresses:
          - 192.168.5.2
    lima0:
      addresses:
        - 192.168.203.214/22
      routes:
      - to: default
        via : 192.168.192.1
      nameservers:
        addresses: [192.168.192.1]
EOF
